version: '2.1'
services:
  nginx:
    restart: always
    mem_limit: 16M
    memswap_limit: 16M
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ENABLE_IPV6=false
      - LE_RENEW_HOOK=docker restart @CONTAINER_NAME@
      - DEFAULT_HOST=localhost


  hackathon:
    restart: always
    mem_limit: 128M
    memswap_limit: 128M
    entrypoint: ["/usr/local/bin/uwsgi", "--ini", "/var/www/uwsgi.ini"]

    build:
      context: .

    depends_on:
      - nginx

    expose:
      - "80"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www

    environment:
      - UWSGI_SOCKET=0.0.0.0:80
      - UWSGI_THREADS=1
      - UWSGI_WORKERS=1
      - UWSGI_MAX_REQUESTS=500
      - UWSGI_SOCKET_TIMEOUT=60
      - UWSGI_HTTP_TIMEOUT=60
      - UWSGI_BUFFER_SIZE=4000
      - UWSGI_STATIC_INDEX = index.html
      - UWSGI_CHECK_STATIC = /var/www
      - VIRTUAL_PROTO=uwsgi
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=localhost
