version: '2.1'
services:
  nginx:
    restart: always
    mem_limit: 32M
    memswap_limit: 32M
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ENABLE_IPV6=false
      - LE_RENEW_HOOK=docker restart @CONTAINER_NAME@
      - DEFAULT_HOST=localhost


  hackathon:
    restart: always
    mem_limit: 64M
    memswap_limit: 64M
    # entrypoint: ['python3.6', '-m', 'http.server', '80']
    entrypoint: ['python3.6', 'run.py']

    build:
      context: .

    depends_on:
      - nginx

    expose:
      - "80"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www

    environment:
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=localhost
